# Generated by Django 5.0.1 on 2024-03-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
